version: 0.0
os: linux
files:
  - source: app.zip
    destination: /usr/local/bin/app_tmp
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: root
